services:
  - type: web
    name: mon-app-php
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ma-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ma-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ma-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: ma-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ma-postgres
          property: password

databases:
  - name: ma-postgres
    plan: free
